### ISSUE TITLE
Error in the inference script. 

### ISSUE THREAD

**Issue by maherr13** [Alibaba-NLP/KB-NER#3]
Hello, Great work. 

I'm trying to obtain the results on colab using one of the checkpoints but I get an error during running the script, the error is from transformers when downloading the tokenizer.

![image](https://user-images.githubusercontent.com/83926003/167885046-f7d3b66b-1f22-46e7-8172-0704338f2ae9.png)

can you check that, please?

**Comment by wangxinyu0922** [comment]
Please check whether you have downloaded the embedding listed in the config file, For example:
```
embeddings:
  TransformerWordEmbeddings-0:
    fine_tune: true
    layers: '-1'
    model: resources/taggers/xlmr-large-pretuned-tuned-new-first_3epoch_1batch_4accumulate_0.000005lr_10000lrrate_multi_monolingual_crf_fast_norelearn_sentbatch_sentloss_nodev_finetune_saving_amz_doc_wiki_v3_ner24/xlm-roberta-large-ft10w 
    pooling_operation: first
```
